/* eslint-disable */
// tslint:disable
/**
 * MICRO SERVICES CURD OPERATIONS
 * 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	export interface AnswerData {
		QuestionId?: string;
		answer?: string;
	}

	/**
	 * <p>ResponseInStatusCode</p>
	 */
	export interface ApiResponse {
		/**
		 * @type {number}
		 * @memberof ApiResponse
		 */
		code?: number;
		type?: string;
		message?: string;
	}

	export interface QuestionData {
		id?: string;
		topicid?: string;
		question?: string;
		optionA?: string;
		optionB?: string;
		optionC?: string;
		optionD?: string;
		QuestionId?: string;
	}

	export interface TaskData {
		id?: string;
		topic?: string;
	}

}
